version: '2'

services:
  ssl:
    build: haproxy
    image: bonitasoft/haproxy
    ports: 
     - "80:80"
     - "443:443"
    links: 
      - "cas:cas"
      - "bonita:bonita"
    depends_on:
      - cas
      - bonita
  cas:
    build: cas
    image: bonitasoft/java-cas
  bonita:
    build: bonita
    image: bonitasoft/bonita
    hostname: bonita
    links: 
      - "cas:cas"
    volumes: 
      - ./bonita/lic:/opt/bonita_lic/
