FROM java:latest

ENV MAVEN_VERSION 3.3.9
ENV MAVEN_HOME /usr/share/maven

RUN mkdir -p /usr/share/maven \
  && curl -fsSL http://apache.osuosl.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz \
    | tar -xzC /usr/share/maven --strip-components=1 \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

WORKDIR /home/cas

ADD . ./
ADD etc/cas-management.properties /etc/cas/cas-management.properties
ADD etc/services /etc/cas/services
ADD etc/user-details.properties /etc/cas/user-details.properties
ADD thekeystore /etc/cas/jetty/thekeystore

RUN ./mvnw clean package
ENTRYPOINT ["./mvnw", "jetty:run-forked"]
